### ISSUE TITLE
Keeping Parser Files in the Repository

### ISSUE THREAD

**Issue by miquelramirez** [aig-upf/tarski#26]
As discussed elsewhere, at one point we had the pre-generated parser files in the repo. 

I removed them because they are incompatible with different versions of the ANTLR Python runtime. I need to double check which is the latest version, and make sure that all setup.py scripts are pointing to the right version before reintroducing them.

**Comment by gfrances** [comment]
At the moment we have these files (again?) in the repo. This was to allow any user to be able to use tarski without needing a full java runtime environment to compile the grammar, etc. I don't like having those large, automatically-generated files in the repo, but being able to do `pip install ...` and have everything working is quite nice, and not sure how to do that otherwise.

However, the versioning issue with the ANTLR Python runtime seems manageable to me. I increased the required version in `setup.py` to the latest one, 4.7.2, which seems to work fine with our current parser-files. Should we consider this satisfactory?

BTW, just for the reference, there is also this package which seems related to this: <https://pypi.org/project/setuptools-antlr/>. I didn't check it carefully, but it seems it does not really do away with the need of having a JRE, etc., unless I'm mistaken.

**Comment by miquelramirez** [comment]
> not sure how to do that otherwise.

A necessary evil I am afraid. Or We can use git lfs for the parser files too. 

> https://pypi.org/project/setuptools-antlr/. I didn't check it carefully, but it seems it does not really do away with the need of having a JRE, etc.

I wasn't aware of that package. Sounds like we should take a look at it.

**Comment by gfrances** [comment]
I would then close this issue - but feel free to reopen if you think otherwise!
