### ISSUE TITLE
Discussion: formula simplifications and LP relaxation

### ISSUE THREAD

**Issue by gfrances** [aig-upf/tarski#75]
As a result of #74 and of previous code by @miquelramirez, we can now expand universal / existential quantifiers in order to e.g. generate logic program - based reachability analysis. When doing so, the formulas we obtain could be greatly simplified by taking into account the values of *static* atoms in the initial state. As an example, in the action `make-product` `Openstacks` we have a precondition

      (:action make-product
        :parameters (?p - product ?avail - count)
        :precondition (and (machine-configured ?p)
	        	       (forall (?o - order)
		        	       (imply (includes ?o ?p) (started ?o)))
		               (stacks-avail ?avail))

which ends up, after expanding the `forall`:

            :precondition (and (machine-configured ?p)
	        	       (and (or (not (includes o1 ?p)) (started o1))
                                (or (not (includes o2 ?p)) (started o2))
                                    ...
                           )
		               (stacks-avail ?avail))

and then after applying the assumption in the relaxation that negative literals are always reachable:

            :precondition (and (machine-configured ?p)
	        	       (and (or True (started o1))
                                (or True (started o2))
                                    ...
                           )
		               (stacks-avail ?avail))

Clearly, we could do away with the expanded conjunction, as it is statically true.
We could implement this simplification straight away. 
However, a better option could be to first check whether the atom can be statically evaluated. In the example above it cannot, as `?p` is still a variable, but it could well be in other cases that we had something such as `(not (includes o2 p5))`, which we could evaluate without any simplifying assumption.

Also, I wonder if it would be better to transform the whole precondition to CNF before applying this simplifications, since of course the role of negated atoms within complex arbitrary formulas might change (think e.g. of a simple precondition `(not (not (includes o1 ?p)))`. The assumptions in Malte's paper are of course that the precondition is already a conjunction of literals, but if we don't have that, as in our case, we might want to adapt the algorithm....?

**Comment by miquelramirez** [comment]
> Clearly, we could do away with the expanded conjunction, as it is statically true.
We could implement this simplification straight away.

Yep, look like a very easy win on a benchmark that has been quite hard to process... not in small part because of redundant constraints we weren't able to determine to be redundant in the first place.

> However, a better option could be to first check whether the atom can be statically evaluated.

That is clean, easy and quite efficient too.

> Also, I wonder if it would be better to transform the whole precondition to CNF before applying this simplifications, since of course the role of negated atoms within complex arbitrary formulas might change (think e.g. of a simple precondition

I think that as part of the universal quantifier elimination you have  to transform everying to NNF. In that case, the particular example you give would be very easy to catch (I think there's a `Visitor` that already does that).

The problem with expanding to CNF is that it is a big gamble: you may have a bad case of ["CNF goo"](https://en.wikipedia.org/wiki/Gray_goo) coming out of that precondition and then have to deal with a few thousand clauses in Python. Which is not fun or efficient.
