### ISSUE TITLE
FstripsReader - plan_metric property of problem object returns None

### ISSUE THREAD

**Issue by anubhav-cs** [aig-upf/tarski#84]
Hi @gfrances @miquelramirez ,

Observed that `problem.plan_metric` property returns `None` for the domains which do have `:metric` defined in the pddl, for example - _IPC-2018->flashfill and organic-synthesis-split_.

Attempted to use _fstripsParser's_ `optimization` and `metricSpec` rules, but couldn't get them to populate the _metric_ _expression_ and _type_ .

This info is required to setup action cost appropriately. Is it possible to populate and retrieve this information using `FstripsReader` or `FstripsParser` classes?

**Comment by miquelramirez** [comment]
Hi @anubhav-cs ,

[this commit](https://github.com/aig-upf/tarski/commit/3b654d85ab79361be96796457feca0ad603b87c7) should solve the issue: see if the all the tests for `tests_fstrips_parsing` are executing correctly. The problem was a typo in `FStripsReader.visitProblemMetric`, that's the event handler that the parser calls whenever it comes across a `(:metric ...)` construct. We were storing the metric on a `metric` attribute, when it should be the `metric_` attribute. I changed that anyways to a property setter, that should be clearer (as there is a `metric` method on the interface of the `Problem` class.

**Comment by gfrances** [comment]
Looks like this is solved, I'll close the issue!
